//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1232434 {
            get {
                object obj = ResourceManager.GetObject("1232434", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902071001660_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902071001660_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902073631785_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902073631785_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902074038936_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902074038936_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902074133860_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902074133860_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902074241828_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902074241828_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902074349852_easyicon_net_321 {
            get {
                object obj = ResourceManager.GetObject("20140902074349852_easyicon_net_321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902074349852_easyicon_net_3212 {
            get {
                object obj = ResourceManager.GetObject("20140902074349852_easyicon_net_3212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902080011708_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902080011708_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902081258131_easyicon_net_24 {
            get {
                object obj = ResourceManager.GetObject("20140902081258131_easyicon_net_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902081608744_easyicon_net_31_6097560976 {
            get {
                object obj = ResourceManager.GetObject("20140902081608744_easyicon_net_31.6097560976", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902081751103_easyicon_net_23_5524475524 {
            get {
                object obj = ResourceManager.GetObject("20140902081751103_easyicon_net_23.5524475524", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082039990_easyicon_net_31_4032634033 {
            get {
                object obj = ResourceManager.GetObject("20140902082039990_easyicon_net_31.4032634033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082344816_easyicon_net_36_5517241379 {
            get {
                object obj = ResourceManager.GetObject("20140902082344816_easyicon_net_36.5517241379", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082441370_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902082441370_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082453888_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902082453888_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082453888_easyicon_net_321 {
            get {
                object obj = ResourceManager.GetObject("20140902082453888_easyicon_net_321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082707271_easyicon_net_48 {
            get {
                object obj = ResourceManager.GetObject("20140902082707271_easyicon_net_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902082852709_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902082852709_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2014090208362136_easyicon_net_29_0909090909 {
            get {
                object obj = ResourceManager.GetObject("2014090208362136_easyicon_net_29.0909090909", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902084041315_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902084041315_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902084227279_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902084227279_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902090124251_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902090124251_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2014090209015449_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("2014090209015449_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902090316490_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902090316490_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902090410761_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902090410761_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _20140902090554250_easyicon_net_32 {
            get {
                object obj = ResourceManager.GetObject("20140902090554250_easyicon_net_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3DAnalystInterpolateProfileGraphCreate32 {
            get {
                object obj = ResourceManager.GetObject("3DAnalystInterpolateProfileGraphCreate32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AbstractsDark01 {
            get {
                object obj = ResourceManager.GetObject("AbstractsDark01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_32x32 {
            get {
                object obj = ResourceManager.GetObject("add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addfile_32x32 {
            get {
                object obj = ResourceManager.GetObject("addfile_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcGISConnectionTest32 {
            get {
                object obj = ResourceManager.GetObject("ArcGISConnectionTest32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcGISExplorer48 {
            get {
                object obj = ResourceManager.GetObject("ArcGISExplorer48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArcGISFileHandler48 {
            get {
                object obj = ResourceManager.GetObject("ArcGISFileHandler48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ARConfig48 {
            get {
                object obj = ResourceManager.GetObject("ARConfig48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backward_32x32 {
            get {
                object obj = ResourceManager.GetObject("backward_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrightNormal32 {
            get {
                object obj = ResourceManager.GetObject("BrightNormal32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_32x32 {
            get {
                object obj = ResourceManager.GetObject("close_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close16 {
            get {
                object obj = ResourceManager.GetObject("Close16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ContMinus50_32 {
            get {
                object obj = ResourceManager.GetObject("ContMinus50_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ContPlus75_32 {
            get {
                object obj = ResourceManager.GetObject("ContPlus75_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CoordinateSystem32 {
            get {
                object obj = ResourceManager.GetObject("CoordinateSystem32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CoverageRelationship32 {
            get {
                object obj = ResourceManager.GetObject("CoverageRelationship32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DataAdd_B_32 {
            get {
                object obj = ResourceManager.GetObject("DataAdd_B_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditCut32 {
            get {
                object obj = ResourceManager.GetObject("EditCut32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditRedo_B_32 {
            get {
                object obj = ResourceManager.GetObject("EditRedo_B_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditUndo_B_32 {
            get {
                object obj = ResourceManager.GetObject("EditUndo_B_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EffectsSwipe32 {
            get {
                object obj = ResourceManager.GetObject("EffectsSwipe32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Extension32 {
            get {
                object obj = ResourceManager.GetObject("Extension32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_32x32 {
            get {
                object obj = ResourceManager.GetObject("forward_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericAddGreen16 {
            get {
                object obj = ResourceManager.GetObject("GenericAddGreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericAddGreen32 {
            get {
                object obj = ResourceManager.GetObject("GenericAddGreen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericBlueAdd_C_16 {
            get {
                object obj = ResourceManager.GetObject("GenericBlueAdd_C_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericBlueAdd32 {
            get {
                object obj = ResourceManager.GetObject("GenericBlueAdd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericDeleteRed32 {
            get {
                object obj = ResourceManager.GetObject("GenericDeleteRed32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericDeleteRedSmall16 {
            get {
                object obj = ResourceManager.GetObject("GenericDeleteRedSmall16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericPauseBlue32 {
            get {
                object obj = ResourceManager.GetObject("GenericPauseBlue32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericPencil16 {
            get {
                object obj = ResourceManager.GetObject("GenericPencil16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GenericWaitTimer32 {
            get {
                object obj = ResourceManager.GetObject("GenericWaitTimer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Group_B_32 {
            get {
                object obj = ResourceManager.GetObject("Group_B_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Group32 {
            get {
                object obj = ResourceManager.GetObject("Group32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HelpSystemBlue48 {
            get {
                object obj = ResourceManager.GetObject("HelpSystemBlue48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerElevation32 {
            get {
                object obj = ResourceManager.GetObject("LayerElevation32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerGeneric32 {
            get {
                object obj = ResourceManager.GetObject("LayerGeneric32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerGeneric321 {
            get {
                object obj = ResourceManager.GetObject("LayerGeneric321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerGeneric3212 {
            get {
                object obj = ResourceManager.GetObject("LayerGeneric3212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerPolygon32 {
            get {
                object obj = ResourceManager.GetObject("LayerPolygon32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerRaster32 {
            get {
                object obj = ResourceManager.GetObject("LayerRaster32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayerTerrain32 {
            get {
                object obj = ResourceManager.GetObject("LayerTerrain32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Layout32 {
            get {
                object obj = ResourceManager.GetObject("Layout32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LayoutChange32 {
            get {
                object obj = ResourceManager.GetObject("LayoutChange32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MapOpen32 {
            get {
                object obj = ResourceManager.GetObject("MapOpen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetaData_New {
            get {
                object obj = ResourceManager.GetObject("MetaData_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataCreateUpdate32 {
            get {
                object obj = ResourceManager.GetObject("MetadataCreateUpdate32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataDocument32 {
            get {
                object obj = ResourceManager.GetObject("MetadataDocument32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataDocument321 {
            get {
                object obj = ResourceManager.GetObject("MetadataDocument321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataEdit32 {
            get {
                object obj = ResourceManager.GetObject("MetadataEdit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataExport32 {
            get {
                object obj = ResourceManager.GetObject("MetadataExport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataImport32 {
            get {
                object obj = ResourceManager.GetObject("MetadataImport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MetadataValidate32 {
            get {
                object obj = ResourceManager.GetObject("MetadataValidate32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ModelBuilderRunModel32 {
            get {
                object obj = ResourceManager.GetObject("ModelBuilderRunModel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_32x32 {
            get {
                object obj = ResourceManager.GetObject("new_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open_32x32 {
            get {
                object obj = ResourceManager.GetObject("open_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagesetup_32x32 {
            get {
                object obj = ResourceManager.GetObject("pagesetup_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PanTool16 {
            get {
                object obj = ResourceManager.GetObject("PanTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RasterImageAnalysisClip32 {
            get {
                object obj = ResourceManager.GetObject("RasterImageAnalysisClip32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RasterImageAnalysisDifference32 {
            get {
                object obj = ResourceManager.GetObject("RasterImageAnalysisDifference32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RasterImageAnalysisMergeAdjacent32 {
            get {
                object obj = ResourceManager.GetObject("RasterImageAnalysisMergeAdjacent32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RasterImageAnalysisOrthoRectify32 {
            get {
                object obj = ResourceManager.GetObject("RasterImageAnalysisOrthoRectify32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RasterImageAnalysisPanSharpen32 {
            get {
                object obj = ResourceManager.GetObject("RasterImageAnalysisPanSharpen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh2_32x32 {
            get {
                object obj = ResourceManager.GetObject("refresh2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Report32 {
            get {
                object obj = ResourceManager.GetObject("Report32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RotatingGlobe32_18 {
            get {
                object obj = ResourceManager.GetObject("RotatingGlobe32-18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_32x32 {
            get {
                object obj = ResourceManager.GetObject("save_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveas_32x32 {
            get {
                object obj = ResourceManager.GetObject("saveas_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectionSelectCircleTool16 {
            get {
                object obj = ResourceManager.GetObject("SelectionSelectCircleTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectionSelectLassoTool16 {
            get {
                object obj = ResourceManager.GetObject("SelectionSelectLassoTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectionSelectLassoTool32 {
            get {
                object obj = ResourceManager.GetObject("SelectionSelectLassoTool32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectionSelectPolygonTool16 {
            get {
                object obj = ResourceManager.GetObject("SelectionSelectPolygonTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectionSelectTool16 {
            get {
                object obj = ResourceManager.GetObject("SelectionSelectTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SignIn32 {
            get {
                object obj = ResourceManager.GetObject("SignIn32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SignIn321 {
            get {
                object obj = ResourceManager.GetObject("SignIn321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpatialAnalystContourTool32 {
            get {
                object obj = ResourceManager.GetObject("SpatialAnalystContourTool32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TableExport32 {
            get {
                object obj = ResourceManager.GetObject("TableExport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TableRecordsZoomTo32 {
            get {
                object obj = ResourceManager.GetObject("TableRecordsZoomTo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User18 {
            get {
                object obj = ResourceManager.GetObject("User18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32 {
            get {
                object obj = ResourceManager.GetObject("User32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32_Add {
            get {
                object obj = ResourceManager.GetObject("User32_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32_Del {
            get {
                object obj = ResourceManager.GetObject("User32_Del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User32_Edit {
            get {
                object obj = ResourceManager.GetObject("User32_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vadfae {
            get {
                object obj = ResourceManager.GetObject("vadfae", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View32 {
            get {
                object obj = ResourceManager.GetObject("View32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomFixedZoomIn16 {
            get {
                object obj = ResourceManager.GetObject("ZoomFixedZoomIn16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomFixedZoomOut16 {
            get {
                object obj = ResourceManager.GetObject("ZoomFixedZoomOut16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomFullExtent16 {
            get {
                object obj = ResourceManager.GetObject("ZoomFullExtent16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomGeneric_B_32 {
            get {
                object obj = ResourceManager.GetObject("ZoomGeneric_B_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomInTool16 {
            get {
                object obj = ResourceManager.GetObject("ZoomInTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomOutTool16 {
            get {
                object obj = ResourceManager.GetObject("ZoomOutTool16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
