//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resee.DataManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resee.DataManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Aspect {
            get {
                object obj = ResourceManager.GetObject("Aspect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Basic_Random {
            get {
                object obj = ResourceManager.GetObject("Basic_Random", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_and_White {
            get {
                object obj = ResourceManager.GetObject("Black_and_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black_to_White {
            get {
                object obj = ResourceManager.GetObject("Black_to_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Bright {
            get {
                object obj = ResourceManager.GetObject("Blue_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Green_Bright {
            get {
                object obj = ResourceManager.GetObject("Blue_Green_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Green_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Blue_Green_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Blue_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blues {
            get {
                object obj = ResourceManager.GetObject("Blues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Brown_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Brown_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Brown_to_Blue_Green_Diverging__Bright {
            get {
                object obj = ResourceManager.GetObject("Brown_to_Blue_Green_Diverging__Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Brown_to_Blue_Green_Diverging__Dark {
            get {
                object obj = ResourceManager.GetObject("Brown_to_Blue_Green_Diverging__Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cold_to_Hot_Diverging {
            get {
                object obj = ResourceManager.GetObject("Cold_to_Hot_Diverging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cool_Grey {
            get {
                object obj = ResourceManager.GetObject("Cool_Grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cool_Tones {
            get {
                object obj = ResourceManager.GetObject("Cool_Tones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cyan_Light_to_Blue_Dark {
            get {
                object obj = ResourceManager.GetObject("Cyan_Light_to_Blue_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cyan_to_Purple {
            get {
                object obj = ResourceManager.GetObject("Cyan_to_Purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cyans {
            get {
                object obj = ResourceManager.GetObject("Cyans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dark_Glazes {
            get {
                object obj = ResourceManager.GetObject("Dark_Glazes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Distance {
            get {
                object obj = ResourceManager.GetObject("Distance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Elevation__1 {
            get {
                object obj = ResourceManager.GetObject("Elevation__1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Elevation__2 {
            get {
                object obj = ResourceManager.GetObject("Elevation__2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Enamel {
            get {
                object obj = ResourceManager.GetObject("Enamel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gray_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Gray_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_Blues {
            get {
                object obj = ResourceManager.GetObject("Green_Blues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_Bright {
            get {
                object obj = ResourceManager.GetObject("Green_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Green_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Green_to_Blue {
            get {
                object obj = ResourceManager.GetObject("Green_to_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Greens {
            get {
                object obj = ResourceManager.GetObject("Greens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Magentas {
            get {
                object obj = ResourceManager.GetObject("Magentas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Muted_Pastels {
            get {
                object obj = ResourceManager.GetObject("Muted_Pastels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orange_Bright {
            get {
                object obj = ResourceManager.GetObject("Orange_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orange_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Orange_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Oranges {
            get {
                object obj = ResourceManager.GetObject("Oranges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Partial_Spectrum {
            get {
                object obj = ResourceManager.GetObject("Partial_Spectrum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Partial_Spectrum_1_Diverging {
            get {
                object obj = ResourceManager.GetObject("Partial_Spectrum_1_Diverging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Partial_Spectrum_2_Diverging {
            get {
                object obj = ResourceManager.GetObject("Partial_Spectrum_2_Diverging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pastel_Terra_Tones {
            get {
                object obj = ResourceManager.GetObject("Pastel_Terra_Tones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pastels {
            get {
                object obj = ResourceManager.GetObject("Pastels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pastels_Blue_to_Red {
            get {
                object obj = ResourceManager.GetObject("Pastels_Blue_to_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pink_to_YellowGreen_Diverging__Bright {
            get {
                object obj = ResourceManager.GetObject("Pink_to_YellowGreen_Diverging__Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pink_to_YellowGreen_Diverging__Dark {
            get {
                object obj = ResourceManager.GetObject("Pink_to_YellowGreen_Diverging__Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Precipitation {
            get {
                object obj = ResourceManager.GetObject("Precipitation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Blue_Bright {
            get {
                object obj = ResourceManager.GetObject("Purple_Blue_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Blue_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Purple_Blue_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Blues {
            get {
                object obj = ResourceManager.GetObject("Purple_Blues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Bright {
            get {
                object obj = ResourceManager.GetObject("Purple_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Red_Bright {
            get {
                object obj = ResourceManager.GetObject("Purple_Red_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Red_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Purple_Red_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_Reds {
            get {
                object obj = ResourceManager.GetObject("Purple_Reds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_to_Green_Diverging__Bright {
            get {
                object obj = ResourceManager.GetObject("Purple_to_Green_Diverging__Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purple_to_Green_Diverging__Dark {
            get {
                object obj = ResourceManager.GetObject("Purple_to_Green_Diverging__Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Purples {
            get {
                object obj = ResourceManager.GetObject("Purples", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_Bright {
            get {
                object obj = ResourceManager.GetObject("Red_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Red_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_to_Blue_Diverging__Bright {
            get {
                object obj = ResourceManager.GetObject("Red_to_Blue_Diverging__Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_to_Blue_Diverging__Dark {
            get {
                object obj = ResourceManager.GetObject("Red_to_Blue_Diverging__Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_to_Green {
            get {
                object obj = ResourceManager.GetObject("Red_to_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_to_Green_Diverging__Bright {
            get {
                object obj = ResourceManager.GetObject("Red_to_Green_Diverging__Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Red_to_Green_Diverging__Dark {
            get {
                object obj = ResourceManager.GetObject("Red_to_Green_Diverging__Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reds {
            get {
                object obj = ResourceManager.GetObject("Reds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Slope {
            get {
                object obj = ResourceManager.GetObject("Slope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spectrum_Full_Bright {
            get {
                object obj = ResourceManager.GetObject("Spectrum_Full_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spectrum_Full_Dark {
            get {
                object obj = ResourceManager.GetObject("Spectrum_Full_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spectrum_Full_Light {
            get {
                object obj = ResourceManager.GetObject("Spectrum_Full_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Surface {
            get {
                object obj = ResourceManager.GetObject("Surface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Temperature {
            get {
                object obj = ResourceManager.GetObject("Temperature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Terra_Tones {
            get {
                object obj = ResourceManager.GetObject("Terra_Tones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Verdant_Tones {
            get {
                object obj = ResourceManager.GetObject("Verdant_Tones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warm_Grey {
            get {
                object obj = ResourceManager.GetObject("Warm_Grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warm_Tones {
            get {
                object obj = ResourceManager.GetObject("Warm_Tones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap White_to_Black {
            get {
                object obj = ResourceManager.GetObject("White_to_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellow_Green_Bright {
            get {
                object obj = ResourceManager.GetObject("Yellow_Green_Bright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellow_Green_Light_to_Dark {
            get {
                object obj = ResourceManager.GetObject("Yellow_Green_Light_to_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellow_Greens {
            get {
                object obj = ResourceManager.GetObject("Yellow_Greens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellow_to_Dark_Red {
            get {
                object obj = ResourceManager.GetObject("Yellow_to_Dark_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellow_to_Green_to_Dark_Blue {
            get {
                object obj = ResourceManager.GetObject("Yellow_to_Green_to_Dark_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellow_to_Red {
            get {
                object obj = ResourceManager.GetObject("Yellow_to_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Yellows {
            get {
                object obj = ResourceManager.GetObject("Yellows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
